packages:
  - 'apps/*'
  - 'packages/*'
  - 'internal/*'

allowBuilds:
  '@parcel/watcher': true
  lefthook: true
  msw: true
  sharp: true
  unrs-resolver: true
minimumReleaseAge: 0
shellEmulator: true
trustPolicy: off
